package com.asosiaciondeasis.animalesdeasis.Model;

public class Vaccine {

    private int id; // Auto-incremented ID generated by the database
    private String animalRecordNumber;
    private String vaccineName;
    private String vaccinationDate;
    private boolean synced;

    public Vaccine(){}
    /**
     * Constructor used when creating a new vaccine to be inserted into the database.
     * The 'id' is not included here because it will be generated by the database upon insertion.
     * This constructor is used from the UI when registering a new vaccine.
     */

    public Vaccine(String animalRecordNumber, String vaccineName, String vaccinationDate) {
        this.animalRecordNumber = animalRecordNumber;
        this.vaccineName = vaccineName;
        this.vaccinationDate = vaccinationDate;
    }

    /**
     * Constructor used when retrieving a vaccine from the database.
     * Includes the 'id' since it's already known and assigned by the DB.
     * This separation of concerns respects SRP by clearly defining two use cases:
     * - creating a new vaccine
     * - mapping a vaccine retrieved from persistence
     */

    public Vaccine(int id, String animalRecordNumber, String vaccineName, String vaccinationDate) {
        this.id = id;
        this.animalRecordNumber = animalRecordNumber;
        this.vaccineName = vaccineName;
        this.vaccinationDate = vaccinationDate;
    }

    public int getId() {return id;}

    public String getAnimalRecordNumber() {return animalRecordNumber;}

    public void setAnimalRecordNumber(String animalRecordNumber) {this.animalRecordNumber = animalRecordNumber;}

    public String getVaccineName() {return vaccineName;}

    public void setVaccineName(String vaccineName) {this.vaccineName = vaccineName;}

    public String getVaccinationDate() {return vaccinationDate;}

    public void setVaccinationDate(String vaccinationDate) {this.vaccinationDate = vaccinationDate;}

    public boolean isSynced() {return synced;}

    public void setSynced(boolean synced) {this.synced = synced;}
}
